### ISSUE TITLE
NSTask isRunning is used

### ISSUE THREAD

**Issue by jkbullard** [etresoft/EtreCheck#2] opened 2015-12-21 02:25 UTC
First, to the developers: Thank you for this program. It's great and very useful.

Investigating a problem in [Tunnelblick](https://tunnelblick.net), a GPLv2 GUI for OpenVPN, I had several of my users run EtreCheck. For some of them the program took more than an hour to run and its output contained a lot programs listed in red under the heading "The following internal tasks failed to complete:" I think I have found the reason.

In EtreCheck's Utilities.m, the `execute:arguments:options:error:` method uses NSTask's isRunning method. The [NSTask Class Reference document](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSTask_Class/index.html#//apple_ref/doc/uid/20000317-SW7) has a curious note about that method:

           "Available in OS X v10.10 through OS X v10.9"

The problem with Tunnelblick was apparently caused by isRunning sometimes returning TRUE even when the task had terminated, and sometimes returning FALSE when the task was still executing. This only happened occasionally, sometimes only weeks after a system boot, usually but not always on heavily loaded systems, and in my users experience, only on OS X 10.11. I think this same problem is causing EtreCheck to believe that an internal task failed to complete.

Looking at the EtreCheck code, I see another problem in `execute:arguments:options:error:` method that Tunnelblick had when doing similar operations: the pipes that the method uses are not emptied until the task has finished executing. This can cause a problem if a task has a lot of output because the buffer can fill up and stall the task (for Tunnelblick, that seemed to happen when a system was heavily loaded and/or low on memory; perhaps OS X uses smaller buffers in that situation). The solution that Tunnelblick used to deal with that was to empty the pipes as the task was running. To fix the problem my users were having, I rewrote the code to (A) use normal files instead of pipes, and (B) avoid the use of isRunning. You might want to do something similar for EtreCheck.

You can find Tunnelblick on GitHub [here](https://github.com/Tunnelblick//Tunnelblick). I have attached [the method](https://github.com/etresoft/EtreCheck/files/68022/runTool.txt) that Tunnelblick now uses to run an external program in the hope that it might help you modify EtreCheck. It does not use Grand Central Dispatch (I believe EtreCheck does) in part because it runs on OS X 10.4 which does not include it. It uses an external function to create a temporary directory for temporary files, but if you don't do operations in parallel you could probably use files with fixed paths.

**Comment by etresoft** [comment] 2015-12-21 03:20
Hello jkbullard,
Thanks for he report. Bu I think the documentation is wrong in this case. There is no indication in the header files about any deprecation. The API notes only mention the change from method to pure properties. Perhaps the fact that this property has a custom getter is screwing things up. There are no formal deprecation annotations in the headers and it does work fine in 10.11.

I would have to see those EtreCheck reports to know more. Having tasks fail to complete is pretty rare. If EtreCheck takes more than an hour to run, it usually means the hard disk has failed. It shouldn't take more than 5 minutes with a mechanical HD and about 2 minutes with an SSD.

**Comment by jkbullard** [comment] 2015-12-21 04:52
I understand that the method is not deprecated. But the problem Tunnelblick was having always involved the isRunning method, and the problem was fixed by removing references to it. I'm sorry if I wasn't clear: I saw situations where a task had completed but the isRunning method was returning TRUE, and I had indirect evidence that a task was still running but the isRunning method returned FALSE.

Since EtreCheck is using the same method and having one of the same problems (seeing a task as still running even though it probably had completed), I still am of the opinion that EtreCheck should be modified to avoid using the method, but of course that's your call.

 [Here is an example of a user's EtreCheck output](https://github.com/etresoft/EtreCheck/files/68096/EtreCheck.output.pdf) that illustrates what happens. The users reported no other problems on their systems, which would not be the case if the hard drive were failing. Booting and using other applications were not slow, for example.

Notice that the EtreCheck "internal tasks" that fail are all uses of "codesign", which rarely takes much time to execute. For example, EtreCheck thinks that it took more than five minutes to execute codesign on
`/System/Library/PreferencePanes/DateAndTime.prefPane/Contents/Resources/TimeZone.prefPane/Contents/Resources/timezoned.app/Contents/MacOS/timezoned`
which on my Yosemite system is single, 53KB file.

If I can be of more help, or if you would like one of my users who had the long EtreCheck executions get in touch with you, please let me know.

**Comment by etresoft** [comment] 2015-12-21 13:08
Hello again jkbullard,
I think the problem is that there is something seriously wrong with that system. The only time codesign has ever failed to complete is when Xcode is running and the user doesn't have an SSD. Xcode is so big that it takes more than 5 minutes. I have never seen the kind of systemic problem with NSTask that you are describing. I am certainly not opposed to making changes to fix problems, but I don't understand this problem yet.

**Comment by jkbullard** [comment] 2015-12-21 14:07
<blockquote>
I think the problem is that there is something seriously wrong with that system.
</blockquote>

I agree. However:
 1. The same problem is being reported by other users. For some of them, Tunnelblick failed (and EtreCheck output included the "Internal task failed to complete" warnings) as soon as the system was fully up after a restart. For others, those problems only happened after days or weeks of the system being up.

 2. The users report *no other problems* on their systems. Use of other apps is normal; only Tunnelblick (and EtreCheck) were affected.

 3. The failing systems did not have any non-Apple programs/agents/daemons/etc. in common except for Flash and Java, which are on most Macs.

I believe that what is seriously wrong is that NSTask's isRunning method is misbehaving. Whether or not that misbehavior is caused by a bug in OS X or a third-party program or malware corrupting OS X, I wanted to fix Tunnelblick to avoid the problem users were having, and not using isRunning has done that.

<blockquote>
The only time codesign has ever failed to complete is when Xcode is running and the user doesn't have an SSD
</blockquote>

Yes, that's exactly the point. It should not take codesign more than five minutes to complete analysis of a 53KB file (the EtreCheck output I posted was from a fairly new system with an SSD). It is my conclusion is that it **didn't** take more than five minutes, but that EtreCheck **thought** it took more than five minutes because isRunning kept returning TRUE even after the task had completed.

<blockquote>
I am certainly not opposed to making changes to fix problems, but I don't understand this problem yet.</blockquote>

The problem is that from what I have observed, the NSTask "isRunning" method does not reliably return a correct result. Incorrect results happen for only a small percentage of users (less than 0.01%) and often only after days or weeks after restarting the computer. By not using isRunning, Tunnelblick no longer exhibits the problems it did when it did use isRunning.

Anyway, thank you again for EtreCheck. I won't bug you any more about this.

**Comment by etresoft** [comment] 2015-12-21 17:19
Hello again jkbullard,
No, please do bug! I just want to identify the problem, that's all. I don't think "isRunning" is a problem because it is only used to check if a task is running after 5 minutes. These codesign tasks should never even be triggering this logic. Now that I look at that "dispatch_after" logic, I don't really like it. If a task completes before then, I want that block to be cancelled. That is going to need some research. 

I think the problem you are describing is related to the pipes and, most likely, the NSFileHandles. The first version of EtreCheck was written in 2 days after all. Since then, I've learned that NSFileHandle is quite unreliable. Perhaps whatever you are doing with Tunnelblick is triggering some OS-level edge case on NSFileHandle. These days, I am ripping out any Apple-designed API and replacing it with lower level routes that Apple might not have broken yet. For example, Apple just broke UTF-8 logic in DOM parsing via NSXMLDocument in 10.11.2 the other day and I had to pull an app from sale.

I think sending output to a file instead of a pipe is one way to handle it. I can do that but I still have to think about how to spawn a task, wait for it, but not too long, collect output from STDOUT and STDERR, and clean everything up. For most people, that sequence works fine as is. Why are your users having this specific problem? Perhaps I can change the code, not break it, and fix it for your users. But this is a critical section of code that will need a fair amount of testing. I can't reproduce this problem so I can't tell if I can fix it for you. But even if I did, I think I might just be hiding some other underlying problem.

So, now that you've made me look at the code, I don't really like it. But in all honesty, it is not something that I'll be able to change right away. And when I do, you'll have to test it. Look for a "pipe_fix" branch in the near future.

John

**Comment by jkbullard** [comment] 2015-12-21 17:41
Thanks, that's interesting. I've never had a problem with NSFileHandle, but then I've never had this problem before, either. I figured that because isRunning has that strange note that it was the most likely culprit.

I don't need you to change EtreCheck, and my users probably don't either, so there's no rush. I mostly wanted to give you a heads-up about a potential problem.

And thanks again for creating EtreCheck and for making it FOSS.

**Comment by etresoft** [comment] 2016-05-15 03:43
I'm going to go ahead and close this. It is pretty old. I just made a significant fix to the process spawning logic. And I just had to re-enable signature checking due to another tit-for-tat in the adware fight. Either this issue is fixed or I want new bug reports on the current logic.

**Closed by etresoft** 2016-05-15 03:43 UTC
